App\Entity\City:
    constraints:
        -   Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
                fields: [name, country]
    properties:
        name:
            - Type:
                  type: string
        latitude:
            - Type:
                  type: numeric
            - Range:
                  min: -90
                  max: 90
        longitude:
            - Type:
                  type: numeric
            - Range:
                  min: -180
                  max: 180
        country:
            - Choice: {callback: [App\Repository\CountryRepository, findAll]}
App\Entity\Country:
    constraints:
        -   Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
                fields: [country_code]
    properties:
        name:
            - Type:
                  type: string
        country_code:
            - Type:
                  type: string
        capital_name:
            - Type:
                  type: string
App\Entity\Weather:
    constraints:
        -   Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
                fields: [time, city]
    properties:
        time:
            - Type:
                  type: datetime
            - GreaterThan: { value: today, groups: [creation] }
        cloudiness:
            - Type:
                  type: string
            - Choice: { callback: getIntensities }
        temperature:
            - Type:
                  type: numeric
        precipitation:
            - Type:
                  type: string
            - Choice: { callback: getIntensities }
        humidity:
            - Type:
                  type: numeric
            - Range:
                  min: 0
                  max: 1
        air_pressure:
            - Type:
                  type: numeric